### ISSUE TITLE
协作请求

### ISSUE THREAD

**Issue by WH-2099** [sukeme/DstServerHelper#1]
你好，我也是一名饥荒联机版玩家。最近在尝试做一些辅助性的脚本，减轻日常服务器维护压力，刚完成了 docker 镜像部分https://github.com/WH-2099/dst-server 。
刚好在 Github 搜索时发现了您的项目，代码（例如解析 meta 文件时先转 json）给了我很多启发，希望与您进一步沟通。
如果有可能的话我觉得我们可以合并项目，协作开发，不知您意下如何？

**Comment by sukeme** [comment]
你好，我不太了解 github，所以不清楚 合并项目，协作开发 具体代表什么。
我看了链接的项目，虽然不太礼貌，但是我觉得 shell 能做的实在有限，单纯开关服的话功能过于基础了，而且类似的脚本也有很多人写过，我不太想继续探索这方面。
meta 文件其实就是保存的 lua 的 table 数据，和 json 结构相似。
如果有觉得我可能知道的，可以直接问我。

**Comment by WH-2099** [comment]
### 关于项目
的确 shell 已经不能满足很多功能的需要了，在受到您项目的启发后，我认为采用 Python 进行重写是更好的解决方案。
最初建立项目时，我只是打算打包一个 docker 镜像，内含有饥荒联机版专用服务器的基础运行环境，完成对 Windows 和 Linux 的跨平台支持，让它能够实现开箱即用。
但在我自己使用的过程中，总是需要自行完成诸如定时重置世界、手动重启更新、重连 klei 验证服务器的一些操作，同时每次配置世界还需要自己创建世界再对配置文件进行拷贝，非常不方便。
所以现在我希望能在打包 docker 镜像时附加一些辅助性工具（就像您项目这样的），我大概整理了一下目前想实现的功能   
 https://github.com/WH-2099/dst-server#%E7%9F%AD%E6%9C%9F 。

### 关于协作
在 GitHub 上这种合作一般有两种形式：
1. 在您为项目选取了开源许可证的情况下，我的项目可以根据对应的许可证条例将您的仓库设为子仓库，而后使用您的源代码。这种情况下，两个项目相对独立。
2. 可以由我们共通建立 GitHub 上的 组织（本质就是个工作小组），将两个项目的代码进行重整后，由这个组织发布唯一的仓库。

个人偏向于第二种方式。

**Comment by sukeme** [comment]
你好，TODO 清单和我希望做的很接近（算上里面的长期目标）。（不过我最近没有着手这些，因为懒）
我想做一个web后台，部署简单，操作友好，这样可以帮助很多不太了解 linux 和开服流程的玩家快速开启服务器，并且对服务器有一定的管理能力，或者直接自动化管理。

你有看我在 readme 里面提到的 [https ://dst.suke.fun/](https://dst.suke.fun/) 吗？这个可以算是一个测试版，但是由于网络原因，有少数 mod 不能保证配置的正确性，不过如果是在本地部署，应该是可以解决这个问题的。
有一个类似的项目 https://github.com/qinming99/dst-admin，不过功能上太简单，主要是作者没有什么意愿更新。

我希望可以做一个更好更方便的后台。我可以接受第二种方式共同协作，但是，由于工作量可能会比预想的大。假如，也许你中途咕咕，或者决定简化很多内容的话，可能会和我的目标有较大出入，那我有可能重新自己弄。

**Comment by WH-2099** [comment]
> [https ://dst.suke.fun/](https://dst.suke.fun/)

我有看过您的测试版后台，很棒！

> [https://github.com/qinming99/dst-admin](https://github.com/qinming99/dst-admin)

之前用过一段时间 dst-admin ，我赞同你的观点。

> 🕊

如果创建组织的话，只要组织内至少还有一名开发者保持活跃就可以保证项目的正常运行，这应该不成问题。

我想我们现在该考虑工作组和项目的命名、采用的开源许可证这些基础问题了，在项目继续向后推进的过程中，我们可以逐步就代码的实际内容再展开讨论。

关于命名，我有点想融入一点饥荒特有的文化元素进去（只是多少有点天真的搞怪心理，hah），但我暂时没有什么太好的候选。
许可证方面的话，我接触的比较多的主要是 MIT 和 GPL。
你怎么看？

**Comment by WH-2099** [comment]
对了还有个问题，我发现项目仓库里没有测试版后台的具体实现代码。不知道关于这部分的内容您是否考虑过一同开源？
这会对许可证的选择有比较大的影响。

**Comment by sukeme** [comment]
可以，本来就是打算全部开源的，不过代码部分写的不好，有考虑重写一下另开一个仓库放，只是暂时还没有弄。（因为一些问题暂时没有办法解决，所以网页的 关于 和 完成 两个页面都还没有写，重写也一放再放
如果要看具体细节，绝大部分代码部分都是 js 完成的，你可以直接看网页的 main.js。
后台做的基本上只有 mod 的下载和设置解析。

命名的话我暂时也没有好的想法，其实只要不太奇怪的话我都可以接受，我不太在意这个，你可以大胆发挥。
关于许可证我更倾向于 GPL，饥荒受众少，开源的越多越好，当然基本也都算是开源的，因为大部分都是 shell，没法加密。不过如果你想采用其他的我也可以接受，我也不太在意这个。

有什么方便的渠道交流吗，感觉这里交流起来不太方便。
