### ISSUE TITLE
有的mod添加时会显示获取modinfo失败

### ISSUE THREAD

**Issue by IcyFeather233** [sukeme/DstServerHelper#4]
在 `dst.suke.asia` 中创建存档时，有的模组能被搜索到，但是无法添加，显示如下：

![image](https://user-images.githubusercontent.com/56245435/226571387-cab72238-4f7a-4250-8a91-527a0607b8e9.png)

**Comment by sukeme** [comment]
你好，是这样的。因为国内网络原因，连接steam的接口不是很稳定，所以获取文件时有时会出问题，就会获取失败。

**Comment by sukeme** [comment]
我也没有什么好的办法，而且我现在不太想弄这个，所以应该是常态，经常失败的话还是建议游戏内调整。

**Comment by IcyFeather233** [comment]
请问在线生成存档的功能会开源吗，我有个境外服务器想也搭建一个，这样生成比较方便，就没有这个获取失败的问题了

**Comment by speater** [comment]
同样想问是否会开源呢

**Comment by sukeme** [comment]
唉主要是写的不好很乱，还有几点应该自动处理的但是没写要手动处理，不好意思开，本来打算重构结果刚开始就咕了。

**Comment by sukeme** [comment]
数据库也没用sqlite用的mysql，所以开起来也有一点麻烦，我找一下直接放这个项目里吧，能不能跑起来看你们的了，加油

**Comment by sukeme** [comment]
已添加，但是不是很好搭建，加油吧

**Comment by IcyFeather233** [comment]
我把后端已经通过 `python3 app.py` 在本地5000端口上跑起来了
![image](https://user-images.githubusercontent.com/56245435/228787240-4ec9777f-2a0f-4035-830c-ed0964d12654.png)
但是想问一下前端是怎么配置访问的呢？直接打开 `dst.html` 这个文件或是在别的端口启动web访问似乎都不能和后端正常交互 想请教一下后端起来后该如何访问前端

**Comment by sukeme** [comment]
你好，我的问题。
本地添加完 readme.md 文件后忘记提交了，现在已经补上

**Comment by IcyFeather233** [comment]
您好，我的 nginx 配置如下：

```
server { 
        listen 8080;

	location ~/tools/ {
  		include      uwsgi_params;
  		uwsgi_pass   127.0.0.1:55555;  # 指向uwsgi,所有请求将转发给uwsgi 处理
  		uwsgi_param UWSGI_PYHOME /home/icyfeather/Downloads/DstServerHelper-master/create-cluster-demo/venv; # 指向虚拟环境目录
 		uwsgi_param UWSGI_CHDIR  /home/icyfeather/Downloads/DstServerHelper-master/create-cluster-demo; # 指向网站根目录
  		uwsgi_param UWSGI_SCRIPT app; # 指定启动程序
	}
}
```

当我访问 `http://localhost:8080/`，显示这个页面：

![image](https://user-images.githubusercontent.com/56245435/228858113-8b0c27d8-08e6-4d1c-9529-55b342870735.png)

当我访问 `http://localhost:8080/tools/`，显示这个页面：

![image](https://user-images.githubusercontent.com/56245435/228858418-8026ae34-4174-47b1-81ae-4d45cdc2cc3c.png)

看起来似乎后端成功运行了，但是仍然不知道如何访问到 `dst.html` 前端网页。是我的 nginx 配的不对吗？我此前没有 uwsgi 使用经验，如果哪里有错误请指教！

**Comment by sukeme** [comment]
你好，现在的情况是后端已经在运行了，nginx 也正确的将请求转发给 uwsgi，但是还没有在 nginx 中配置好前端文件的规则，可以找教程了解一下nginx。
我的这部分配置信息如下，可以作为参考：
```
listen 80;
index dst.html;  # html 文件
root /www/wwwroot/dst.suke.fun;  # 指向网站根目录
```

**Comment by IcyFeather233** [comment]
您好！我已经搭建起来了服务，感谢您之前的耐心解答！只是我这里还有一个问题，请问一下您是如何配置域名访问的呢，我现在只能通过端口访问，能否分享您nginx配置中有关域名访问的部分以供参考？万分感谢！

**Comment by sukeme** [comment]
```
server_name dst.suke.asia;
```

**Comment by IcyFeather233** [comment]
感谢！我已经配置好了https域名访问，在这里分享一下搭建细节：

# 环境说明

- OS: Linux Mint 21 / Debian 11 均测试成功
- Tools: Nginx / MySQL
- Python: 9 / 10 均测试成功


# 克隆仓库

```
cd /opt/html
git clone https://github.com/sukeme/DstServerHelper.git
```

```
cd DstServerHelper/create-cluster-demo/venv/
```

# 配置数据库

root 登陆：
```
sudo mysql -u root -p
```

创建用户 dst 以及数据库 dst：
```
mysql> create user 'dst'@'localhost' identified by 'password';
Query OK, 0 rows affected (0.20 sec)

mysql> create database dst;
Query OK, 1 row affected (0.02 sec)

mysql> grant all privileges on dst.* to 'dst'@'localhost';
Query OK, 0 rows affected (0.02 sec)
```

退出后，创建 dst.sql 文件，输入以下内容：

```
# Dump of table modinfo
# ------------------------------------------------------------

DROP TABLE IF EXISTS `modinfo`;

CREATE TABLE `modinfo` (
  `mod_id` bigint unsigned NOT NULL,
  `update_time` int unsigned NOT NULL,
  `check_time` int unsigned NOT NULL,
  `mod_type` tinyint unsigned NOT NULL,
  `mod_info` json NOT NULL,
  PRIMARY KEY (`mod_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



# Dump of table running
# ------------------------------------------------------------

DROP TABLE IF EXISTS `running`;

CREATE TABLE `running` (
  `mod_id` bigint unsigned NOT NULL,
  `start_time` int unsigned NOT NULL,
  `end_time` int unsigned NOT NULL DEFAULT '0',
  `waitting` tinyint unsigned NOT NULL DEFAULT '0',
  `mod_info` json NOT NULL,
  PRIMARY KEY (`mod_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

dst 登陆 mysql：

```
sudo mysql -u dst -p
```

在数据库 dst 中建表：

```
use dst;

source dst.sql;
```


修改 `mysql_login.cnf` `steamapikey.txt` (在 https://steamcommunity.com/dev/apikey 这里申请) 和 `config.ini`

然后运行 `uwsgi ./config.ini` 会报错：

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/html/DstServerHelper/create-cluster-demo/venv/log/app.log'
```

需要创建 `log` 文件夹：`mkdir log`

修改 `sql_task.py` 中的 config 部分

自己创建 venv 环境，进入之后首先要 `sudo apt install libmysqlclient-dev` 不然后面 mysqlclient 会安装失败

`pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ --target=xxx/site-packages` 安装依赖到指定 venv 环境中

`pip install uwsgi --target=xxx/site-packages` 

在 `config.ini` 中要加一行：

```
pythonpath = /opt/html/DstServerHelper/create-cluster-demo/venv/your_new_venv/lib/python3.9/site-packages
```

用于指定 uwsgi 运行时的 python 环境

然后运行 `screen ./your_new_venv/bin/uwsgi ./config.ini`，不出意外的话就成功了

----------

另外给出小小的建议，python venv 环境不应一同上传到仓库中，只保留 `requirements.txt` 文件即可，应当自行创建，不然如 python 版本不同似乎会有 bug。venv 目录应当与代码部分平级，资源文件可以放在平级的 `assets` 目录中，数据库的创建如果可以自动化会更好。这几天如果我有时间的话尝试一下（也可能咕咕

最后，非常感谢您对代码的开源以及耐心指导！

**Comment by sukeme** [comment]
哇，你真厉害，虽然给的一些信息不全甚至错了也成功搭建起来了，还整理这么详细。
关于提出的建议，确实现在的结构很不规范，这也是我一直没开源的原因之一hh（其它原因是一些未能解决的代码层面的问题，关于高级的模组设置方面），原本准备重构然后就咕咕咕了。
虚拟环境一同上传是因为由于一些需要，修改了 steam 库的几个设置项，由于时间太久，我不记得修改的原因了，为了防止跑不起来，就干脆把整个目录全丢进来了。当然主要是我整理了一下发现太麻烦加上一些东西都忘记了，就偷懒全上传了。
笑死，原来 `mysql_login.cnf` 文件压根没用到吗，我还以为用的这个呢。
很多东西确实不完善，只是试着写出来，有很多问题，目前我也放弃这个网站了，未来有可能重构加入到不知道会不会有的后台管理。
如果你对饥荒有很大兴趣的话，可以看看这个 https://github.com/Fire-Paw-DST-Manager/DST-Common ，里面一些代码也不太好，但我没想到好的办法优化。或者有其它饥荒代码方面的分享吗？

**Comment by IcyFeather233** [comment]
https://github.com/Fire-Paw-DST-Manager/DST-Common 这个仓库是做什么的呢？没有 README 我不太能搞懂
我知道一个饥荒开服脚本：https://github.com/PNCommand/DSTServerManager ，是用shell写的，我之前用这个开服务器

**Comment by sukeme** [comment]
emm，是为开服工具做的准备工作
klei_id：采用与饥荒内部相同的方式实现玩家 id 的编码与解码，可用于离线玩家的信息展示与修改
klei_tex：python 实现的饥荒贴图文件 `tex` 转 `png`，与不经压缩单纯打包的 `png` 转 `tex`，用于部分饥荒图片的显示
klei_map：将世界存档文件内地图信息转为 `svg` 格式，用于世界地图的展示与修改
klei_zip：采用与饥荒内部相同的方式对数据进行压缩与解压缩。部分数据文件饥荒会先压缩、处理再保存，可用于获取这部分信息

klei_map 这个，存档内部关于地图信息还有几份其它数据，但我目前不知道怎么处理。其次是转换的算法速度较慢，但我不知道怎么优化。

开服脚本方面的东西我应该都了解，想了解的是更多更细节的，可以实现一个相对完善的后台管理的知识点。比如以上这些，可以展示与处理 玩家信息、世界地图与物品信息。目前缺少的是关于模组的，比如模组添加了世界设置、游戏模式等，这种信息应该怎么自动获取。或者其它我暂时还没考虑到的知识点。

**Comment by IcyFeather233** [comment]
抱歉这方面我也了解不多
想问一下你用的是什么开服工具呢？

**Comment by sukeme** [comment]
https://github.com/qinming99/dst-admin

**Comment by IcyFeather233** [comment]
我晚上体验了一下，这个用docker然后web管理体验很不错，但是还是有些缺点，比如要结合你的这个项目来生成zip或者tar直接导入来生成世界会比较方便，web管理界面自己是不支持搜索mod并添加的，这也导致不能很方便的后续修改mod设置等。

**Comment by sukeme** [comment]
是的，这个后台功能性和自由度不高，而且作者目前没有进一步优化的想法。

**Comment by IcyFeather233** [comment]
关于你说的想知道更多模组部分的细节，你的网站不是可以网页端选择配置mod然后生成配置文件吗，你想研究的是哪一个部分呢

**Comment by sukeme** [comment]
如果在创建世界时勾选了一些模组比如岛屿冒险，你会发现世界预设中多出了一些模组物品，除此之外，模组还可以操控其它一些设置，这部分现在的网站是没法获取的，现在只是解析`modinfo.lua`获取作者提供的模组设置项

**Comment by sukeme** [comment]
其实这部分主要问题在于，会主动将模组物品做适配添加入世界预设，往往代表着作者团队确实在用心做模组，并且受众也不会少。这也是虽然这种模组数量不多，但是我依然想要把这部分处理好的部分原因，另一部分是我不想只是提供残缺的体验。

**Comment by IcyFeather233** [comment]
我从网上找了个结构模板：

```
Cluster_Name  # 以集群方式提供服务，地面和洞穴是两个独立的服务器进程
├── cluster.ini  # 集群配置
├── cluster_token.txt  # 集群认证码
├── adminlist.txt  # 管理员名单，克雷的 ID（KU_XXXXXXXX），一行一个
├── blocklist.txt  # 封禁名单，SteamID64，一行一个
├── whitelist.txt  # 特权名单，克雷的 ID（KU_XXXXXXXX），一行一个
├── Master  # 主服务器进程（地面）
│   ├── server.ini  # 服务器配置
│   ├── modoverrides.lua  # mod 的设置
│   ├── worldgenoverride.lua  # 世界（地形、生物等）的设置
│   └── save  # 存档
│       └── ...
├── Caves  # 洞穴服务器
│   ├── server.ini  # 服务器配置
│   ├── modoverrides.lua  # mod 的设置
│   ├── worldgenoverride.lua  # 世界（地形、生物等）的设置
│   └── save  # 存档
│       └── ...
└── mods  # mod 相关
    └── dedicated_server_mods_setup.lua  # mod 加载设定
```

结合本项目web下载的文件分析，生成世界的结构似乎不需要 `mods` 文件夹。

我想你的意思是一般的模组只会影响 `modoverrides.lua` 文件的内容，但是有的模组会影响 `worldgenoverride.lua` 文件，我们需要自动处理这一部分？

**Comment by sukeme** [comment]
是的，可以这么理解。

**Comment by IcyFeather233** [comment]
我去某个饥荒mod制作群里请教了一下，这部分似乎在 `modworldgenmain` 里面？

**Comment by sukeme** [comment]
是的，但是没法获取到具体改动了什么。运行环境饥荒也是直接把`GLOBAL`传进去了，所以也没法模拟一个出来

**Comment by IcyFeather233** [comment]
我找到一个很不错的开服项目，里面集成了配置mod的功能，https://github.com/hujinbo23/dst-admin-go，看起来很好用

**Comment by sukeme** [comment]
是的，我也知道这个项目，但是其实并不能从中学习到我需要的知识。因为看饥荒部分的代码的话，你会发现基本是源自这个项目的
