### ISSUE TITLE
网页模组搜索功能无法使用

### ISSUE THREAD

**Issue by IcyFeather233** [sukeme/DstServerHelper#5]
网页 `https://dst.suke.asia/` 的模组搜索功能出错，不管搜什么都显示 “在搜索了”，打开 F12 显示 502 Bad Gateway。

![image](https://user-images.githubusercontent.com/56245435/228792673-14e2ae02-a541-4d79-8957-a7cbd958fde2.png)

**Comment by sukeme** [comment]
你好，后端忘开了，现在已经开起来了
