### ISSUE TITLE
worldgen_customization.tex 怎么转成webp

### ISSUE THREAD

**Issue by carrot-hu23** [sukeme/DstServerHelper#6]
请问您是用什么方式把 worldgen_customization.tex 装成 worldgen_customization.webp的？

**Comment by sukeme** [comment]
你好，因为这个网页demo我没有继续完善的打算，所以目前依然需要自行使用工具转换。
如果没有转换工具，可在klei论坛中搜索 tex 等关键词，有一些玩家发布的软件可以使用。

**Comment by carrot-hu23** [comment]
好的，感谢
